---
version: 2
project_name: btrfs-backup

builds:
  - id: linux-amd64
    main: ./cmd/btrfs-backup
    binary: btrfs-backup-linux-amd64
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X btrfs-backup/internal/cli.version={{.Version}}

  - id: linux-arm64
    main: ./cmd/btrfs-backup
    binary: btrfs-backup-linux-arm64
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X btrfs-backup/internal/cli.version={{.Version}}

archives:
  - formats: [binary]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
