---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

"on":
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Lint code
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Run tests
        run: go test -v ./...

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Run semantic release
        uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          changelog-generator-opt: "emojis=true"
          github-token: ${{ steps.app-token.outputs.token }}
